### ISSUE TITLE
Please clarify what SAML function this project provides

### ISSUE THREAD

**Issue by john-aws** [Clever/saml2#130]
Hi, as far as I can tell, this project can only be used to implement a Service Provider, but not an Identity Provider. If that's indeed true, it would be helpful to clarify this in the README because the presence of both ServiceProvider and IdentityProvider classes gives the impression that the code can be used to implement both.

**Comment by john-aws** [comment]
@jstephens7 You might also want to take a look at [mcguinness/saml-idp](https://github.com/mcguinness/saml-idp) if you want to host your own simple IdP.

**Comment by odnarb** [comment]
+1
As someone who has never used or implemented SAML 2.0 this package went only halfway in what could've been great, useful, and helpful. However I wasted hours trying to use this AS AN IDP.

Now I know what an SP is this package is fine, but still confusing.

Yes, it helps to have a solid understanding of the SAML 2.0 flow. But for me, I have to get a solution up and running FAST.
This package has sadly fallen short.

I know, I could make a PR instead of complaining, but I just do not have the time. It would probably help tremendously too.
