### ISSUE TITLE
set/change validUntil

### ISSUE THREAD

**Issue by Jarleborn** [Clever/saml2#158]
Hi

Our metadata expires today and I can't find how i reneew the metadata. I've tried to change cert/key and to re-create the metadata and neither of those works..

**Comment by cozmo** [comment]
How you handle certificate rollover is somewhat out of the domain of this library, but you can use `alt_certs` and `alt_private_keys` to allow exposing, signing and accepting signatures with multiple certificates during a rollover period. Generally you need the Identify providers to update and pull in your new certs, so you'll spend some amount of time before the expiration exposing the new and old certificates, so as to give them time to update. 

Closing this since the library supports this and it's more up to consumers to decide how they want to handle cert rotation, but please re-open if feel this is incorrect etc.
