### ISSUE TITLE
Can I use this library in React Native?

### ISSUE THREAD

**Issue by ashvinramana** [Clever/saml2#169]
I want to implement SSO (single sign-on) using SAML in react native.
Can I use this library in React Native?

Thanks in advance

**Comment by abrantes01** [comment]
@ashvinramana did you manage to solve your problem?

**Comment by cozmo** [comment]
The nature of SAML would prevent you from doing this. For a SAML exchange to work correctly both the IDP and the SP have a public and private key that they use to sign assertions that they then pass back and forth to facilitate the login

You wouldn't be able to do this in a client application (react native, fully native etc) for two reasons. 
1. You have no public URL. The IDP can't redirect the user to your app, since there's no standard URL. It's possible you could do something funky with custom URL schemes, BUT
2. You can't put a private key in your application, since then anyone who installs your application could get your private key and use it to break/intercept/forge SAML logins, stealing information and completely removing the security of the SAML flow. 

As such you'd not want to use this library in your app. If you want to do SAML logins into a mobile application you'd want to make a web server that handles the logins, and then have your application communicate with that server. How that is implemented is out of scope of this library, and up to you to decide.
