### ISSUE TITLE
Push tags to GitHub

### ISSUE THREAD

**Issue by gabegorelick** [Clever/saml2#185]
It would be nice if releases were tagged and pushed to GitHub. https://github.com/Clever/saml2/releases shows nothing since v1.0.3 in 2015.

**Comment by cozmo** [comment]
We don't publish GitHub tags because the source code is compiled (from coffeescript to JS) during the build process, so using the GitHub tags to pull down the source won't let you actually use the library (you'd need to build it first). This wasn't the case back in 2015, which is why we published tags then. 


Unrelated but we had an issue where we weren't publishing npm versions but that was fixed in https://github.com/Clever/saml2/pull/191 - If you still would like GitHub tags to be published I'd love to understand why, but closing this issue until then.

**Comment by gabegorelick** [comment]
Lack of tags was an issue when it wasn't clear what the released version was (there was a significant period of time where 2.0.4 was committed to master but not published to npm). If the plan going forward to is automatically publish everything to npm, then tags are not really a big deal to me.
