### ISSUE TITLE
Is it impossible to use with angular?

### ISSUE THREAD

**Issue by rahul0004** [Clever/saml2#195]
Hi I have an angular 8 application and wanted to implement SAML with keyclock for authentication of angular application. 

Is it possible using this library ? 

If yes can you please share a code snippet for the same.

**Comment by cozmo** [comment]
Due to the nature of SAML, you need to run this library on the server side (in a node JS process). Running it on the client side would mean you would have to leak your private keys etc. 

This doesn't stop you from using it with an angular application, much the less - nothing about your client side architecture should impact your use of this lib or not, but it needs to be run on the server side not the client side so as to not leak secrets.
