### ISSUE TITLE
Add debug

### ISSUE THREAD

**Issue by nathanleiby** [Clever/saml2#5]
Quite useful to see a bit more information from the library at times (e.g. raw assertion, decrypted assertion).

**Comment by templaedhel** [comment]
We've gotten a lot better at handling and debugging failed responses. Seeing as this issue is > a year old I'm comfortable closing.

**Comment by nathanleiby** [comment]
Sounds good!

**Comment by kellertobias** [comment]
Maybe the debugging/handling of failed responses is a lot better, but debug would still be helpful.
it took me 2 hours to figure out that my certificate string is actually empty because of a simple (and nearly unrecognizable) typo. 

Error of saml2-js was "Error: Invalid Certificate". Not really helpful!

Maybe some internal status flags (e.g. what kind of certificate error, because invalid certificate could mean many many things, such as necessary `---BEGIN CERTIFICATE---` or wrong format or an empty file)

otherwise neat package :), lets see if it passes the acceptance test on thursday
